#+TITLE: MetaHash: Жёлтая бумага, техническая документация
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style> ol ol li { list-style: lower-alpha !important; } </style>

* Аннотация
  2017-й стал годом бума децентрализованных технологий. Парадигма
  децентрализации решает несколько ключевых вопросов:

  * вопросы доверия к системе и контролирующим органам,
  * масштабируемость и надёжность системы,
  * а также, необходимость участия третьих сторон.

  Однако, платформа децентрализации и рынок приложений ограничены двумя
  основными факторами. Во-первых, географическое распределение узлов из-за
  недостаточной инфраструктуры соединений вызывает медленную синхронизацию и
  проверку данных. Во-вторых, уязвимость распределённых сетей перед атакой
  51%[fn:1] оставляет желать лучшего с точки зрения безопасности и доверия.

  #MetaHash преодолевает эти препятствия, вводя динамические роли узлов и
  реализуя фрагментированное криптографическое доказательство. Одновременно
  уменьшая объём передаваемых данных, этот подход оптимизирует синхронизацию
  сети и решает проблемы трансконтинентальной передачи и архивирования данных.

  Кроме того, этот подход привёл к созданию #MetaPoS, многоуровневой системы
  консенсуса, повышающей устойчивость сети к атакам 51% до 90%. Используя
  проприетарные технологии #MetaSync и #MetaPoS, команда #MetaHash создала
  #TraceChain, самый быстрый протокол блокчейна на сегодняшний день.

  Результаты нагрузочного теста показывают пропускную способность выше 50 000
  транзакций в секунду[fn:2]. Методы и результаты можно найти в этом документе.

  #MetaHash — это высокопроизводительный и недорогой блокчейн нового поколения.
  Высокая скорость подтверждения и низкие комиссии за обработку данных
  обеспечивают поддержку микротранзакций и позволяют работать с
  децентрализованными приложениями почти в реальном времени.

[fn:1] https://www.investopedia.com/terms/1/51-attack.asp

[fn:2] В широкой полосе пропускания (до 600 000 транзакций в секунду)


* Цели проекта
** Краткосрочный этап
   1. Высокоскоростной мультиблокчейн на основе протокола #TraceChain:
      1) Дизайн геораспределённой сети с минимальным временем синхронизации при
         сохранении максимальной пропускной способности данных.
      2) Выбор модели консенсуса, обеспечивающей минимальное время подтверждения
         транзакции при сохранении неизменности транзакции.
      3) Сохранение криптографических доказательств владения активами при
         уменьшении объёма хранимых и передаваемых данных.
      4) Подбор оптимальной балансировочной модели.
      5) Устранение проблем чрезмерного хранения данных в проверенной временем
         сетевой структуре блокчейна.
      6) Разрешение нелинейной проверки данных блокчейна.
      7) Избежание хард-форков при развёртывании крупных обновлений программного
         обеспечения.
      8) Решение проблемы слияния блокчейнов после разделения сети.

   2. Децентрализованное хранилище

   3. #MetaApps: виртуальных хостинг приложений.

   4. #MetaDNS: распределённый сервис доменных имён.

   5. #MetaGate: мультивалютный кошелёк и браузер DApp (децентрализованных
      приложений).

** Среднесрочный этап
   1. Совместное использование мобильных ресурсов (сотовая и спутниковая связь,
      передача данных). Консенсус для мобильных устройств.

   2. Магазин DApp.

   3. Цифровая идентификация с биометрическими данными.

   4. IoT (интернет вещей) возможности и совместимость.

   5. Универсальная система репутации.


